- name: Ensure all tools are installed
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - make
          - gcc
          - g++
          - build-essential
          - libhiredis-dev
          - uuid-dev
          - pkg-config
          - libssl-dev
          - libcurl4-openssl-dev
          - zlib1g-dev
          - libc6-dev

        state: present



# To run do a ansible-playbook -i
