#define REDIS_GIT_SHA1 "ded8d993"
#define REDIS_GIT_DIRTY "53"
#define REDIS_BUILD_ID "lhotse102-1730826449"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
